### PR TITLE
perf: optimise the performance of access_log

### PR DESCRIPTION
**Pull request by Skyenought**
#### What type of PR is this?
perf

#### Which issue(s) this PR fixes:
https://github.com/cloudwego/cwgo/issues/107

### CODE REVIEW

**Comment by li-jin-gou** [comment]
补充一下 benchmark

**Comment by li-jin-gou** [comment]
有 break change 嘛？

**Comment by Skyenought** [comment]
无

**Comment by li-jin-gou** [comment]
> 无

修改一下 commit messgae 吧

**Comment by Skyenought** [comment]
修改后

goos: darwin
goarch: amd64
pkg: github.com/hertz-contrib/logger/accesslog
cpu: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
Benchmark_AccessLog
Benchmark_AccessLog/Base
Benchmark_AccessLog/Base-8         	  365762	      3361 ns/op	     288 B/op	       5 allocs/op
Benchmark_AccessLog/DefaultFormat
Benchmark_AccessLog/DefaultFormat-8         	1000000000	         0.0000594 ns/op
PASS

修改前

goos: darwin
goarch: amd64
pkg: github.com/hertz-contrib/logger/accesslog
cpu: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
Benchmark_AccessLog
Benchmark_AccessLog/Base
Benchmark_AccessLog/Base-8         	  280884	      3786 ns/op	     296 B/op	       6 allocs/op
Benchmark_AccessLog/DefaultFormat
Benchmark_AccessLog/DefaultFormat-8         	1000000000	         0.0000559 ns/op
PASS

**Review by li-jin-gou — APPROVED** [review]

**Pull request merged**
