### PR TITLE
feat: upgrade zerolog version and set context

### LINKED ISSUE #38: zerolog CtxInfo 在调用时并没有把 ctx 传入 logger
这样会造成 zerolog hook 获取 ctx 为 nil

https://github.com/hertz-contrib/logger/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

### PR DESCRIPTION
**Pull request by liuzhaowei55**
#### What type of PR is this?

fix

#### What this PR does / why we need it (English/Chinese):

1. 升级 zerolog 版本从 1.28.0 -> 1.30.0
2. logger.CtxLogf() 传递 ctx 到 zerolog

#### Which issue(s) this PR fixes:

Fixes #38

### CODE REVIEW

**Review by li-jin-gou — APPROVED** [review]

**Review by li-jin-gou — CHANGES_REQUESTED** [review]
CLA need to sign

**Comment by li-jin-gou** [comment]
@liuzhaowei55  我翻了一个之前的 issue 可以看下,感觉这么加有问题. https://github.com/cloudwego/hertz/issues/749

**Comment by liuzhaowei55** [comment]
> @liuzhaowei55 我翻了一个之前的 issue 可以看下,感觉这么加有问题. [cloudwego/hertz#749](https://github.com/cloudwego/hertz/issues/749)

https://github.com/rs/zerolog/blob/06ec071bc1eddfbec464bcda042f2504b1126947/ctx.go#L45

https://github.com/rs/zerolog/blob/06ec071bc1eddfbec464bcda042f2504b1126947/event.go#L426

我看了下两个 `Ctx()` 调用不太一样，`ctx.go#L45` 会生成新的 Logger，`event.go#L426` 是在 `*Event` 上更新的

**Comment by li-jin-gou** [comment]
PATL @rogerogers

**Review by li-jin-gou — APPROVED** [review]

**Pull request merged**
