### PR TITLE
Expanded Hertz's logging middleware for http requests

### PR DESCRIPTION
**Pull request by edufriendchen**
#### What type of PR is this?

feat：Expand Hertz on HTTP request response logging middleware

#### What this PR does / why we need it (English/Chinese):

English: Expanded Hertz's logging middleware for http requests
中文：扩展了Hertz针对http请求的日志中间件

### CODE REVIEW

**Comment by rogerogers** [comment]
ci need fix

**Comment by edufriendchen** [comment]
> ci need fix

I'm sorry to ask if I need to manually raise an Issue and point to it. I'm not experienced. I'm sorry!

**Comment by li-jin-gou** [comment]
Thanks and we will not accept this pr because I think it is the same as access_log.  https://github.com/hertz-contrib/logger/tree/main/accesslog.

**Comment by EduFriendChen** [comment]
Yes, this middleware is the inspiration I got from Gin transfer Hertz，Unexpectedly The access_log is already available， I'm sorry to disturb everyone.

**Comment by edufriendchen** [comment]
> Thanks and we will not accept this pr because I think it is the same as access_log. https://github.com/hertz-contrib/logger/tree/main/accesslog.

Yes, this middleware is the inspiration I got from Gin transfer Hertz，Unexpectedly The access_log is already available， I'm sorry to disturb everyone.

**Pull request closed without merging**
