### PR TITLE
fix(bugfix): Do not create new logger when calling CtxLogf

### LINKED ISSUE #749: 请问 为什么handler 中触发了 panic 却没有异常堆栈信息
如下图所示，我在handler 里之间 panic 了，然后用 postman 访问是 500 错误，但是控制台没有输出异常堆栈信息，请问要怎么让他输出呢
image

image

服务器启动代码如下：
```go
func serverInit() {
	h := server.Default(
		server.WithHostPorts(viper.Conf.App.HostPort),
		server.WithExitWaitTime(60),
	)
	//h.Use(middleware.GlobalErrorHandler)
	register(h)
	h.Spin()
}
```

### PR DESCRIPTION
**Pull request by sillen102**
#### Which issue(s) this PR fixes:
Fixes https://github.com/cloudwego/hertz/issues/749

### CODE REVIEW

**Comment by Duslia** [comment]
It won't create logger. It will use logger in `ctx`

**Review by li-jin-gou — APPROVED** [review]

**Comment by li-jin-gou** [comment]
CLA need to sign @sillen102 ❤️

**Comment by sillen102** [comment]
> CLA need to sign @sillen102 ❤️

Done!

**Comment by li-jin-gou** [comment]
> [CLA assistant check](https://cla-assistant.io/hertz-contrib/logger?pullRequest=28) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hertz-contrib/logger?pullRequest=28) before we can accept your contribution.
> 
> **Silvio Sabo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hertz-contrib/logger?pullRequest=28) it.

CLA was not signed successfully and I'll paste the code to fix it

**Pull request closed without merging**
